### ISSUE TITLE
Update response actions to better format

### ISSUE THREAD

**Issue by brent-spyder** [spyderbat/spyctl#37]
Right now it looks like this:
```
  response:
    default:
      severity: high
    actions:
    - podSelector:
        matchLabels:
          env: prod
      actionName: kill-pod
      severity: critical
    - podSelector:
        matchLabels:
          env: dev
      actionName: webhook
      url: https://example.com
      template: yaml
      severity: high
```

This is confusing.. generating a redflag or opsflag should be its own action. The default field should be a list of actions with no selectors. The actions field should be a list of actions, but at least one selector is required.
```
  response:
    default:
    - makeRedFlag:
        content: "X is happening."
        impact: "Because X is happening it means this.."
        severity: high
    - makeOpsFlag:
        content: "This ops issue is happening"
        severity: high
    actions:
    - agentKillPod:
        podSelector:
          matchLabels:
            env: prod
    - makeRedFlag:
        podSelector:
          matchLabels:
            env: prod
        content: "X is happening in production."
        impact: "Because X is happening it means this.."
        severity: critical
    - webhook:
        podSelector:
          matchLabels:
            env: dev
        urlDestination: https://example.com
        template: yaml
    - makeRedFlag: 
        podSelector:
          matchLabels:
            env: dev
        content: "X is happening in the dev environment."
        impact: "Because X is happening it means this.."
        severity: low
```
